//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesDBNew.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Movie
    {
        public int id { get; set; }
        [StringLength(60, MinimumLength = 3)]
        public string Title { get; set; }
        [Display(Name = "Release Date"), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}"), DataType(DataType.Date)]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        [Required(ErrorMessage = "Enter Something"), RegularExpression(@"^[A-Z]+[a-zA-Z'-'\s\-]*$"), StringLength(30)]
        public string Genre { get; set; }
        [Range(0,1000), DataType(DataType.Currency)]
        public decimal Price { get; set; }
    }
}
